CREATE TABLE review
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    created                   TIMESTAMP WITHOUT TIME ZONE,
    updated                   TIMESTAMP WITHOUT TIME ZONE,
    deleted                   BOOLEAN NOT NULL,
    version_id                BIGINT NOT NULL REFERENCES offer_article_version (id),
    anti_plagiarism           VARCHAR(255),
    first_reviewer_file_uuid  UUID REFERENCES file_metadata (uuid),
    second_reviewer_file_uuid UUID REFERENCES file_metadata (uuid)
);