CREATE TABLE user_data
(
    user_id     BIGINT NOT NULL,
    email       VARCHAR(255),
    first_name  VARCHAR(255),
    second_name VARCHAR(255),
    CONSTRAINT pk_user_data PRIMARY KEY (user_id)
);

ALTER TABLE user_data
    ADD CONSTRAINT FK_USER_DATA_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY;