CREATE TABLE user_data
(
    user_id     BIGINT NOT NULL,
    email       VARCHAR(255),
    first_name  VARCHAR(255),
    second_name VARCHAR(255),
    CONSTRAINT pk_user_data PRIMARY KEY (user_id)
);

ALTER TABLE user_data
    ADD CONSTRAINT FK_USER_DATA_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);
CREATE INDEX email_index ON user_data (email);

ALTER TABLE users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY;

INSERT INTO users (password, roles)
VALUES ('$2a$10$/7xDoZLpDfCH0TKfaLlYg..hwXagdy0B5/zye05YYAUt84Z0SzhHy', 'USER');

INSERT INTO user_data (user_id, email, first_name, second_name)
VALUES (lastval(), 'user@mail.ru', 'User', 'Userov');
INSERT INTO users (password, roles)
VALUES ('$2a$10$/7xDoZLpDfCH0TKfaLlYg..hwXagdy0B5/zye05YYAUt84Z0SzhHy', 'ADMIN');
INSERT INTO user_data (user_id, email, first_name, second_name)
VALUES (lastval(), 'admin@mail.ru', 'Admin', 'Adminov');
