CREATE TABLE offer_article
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    owner_id BIGINT REFERENCES users(user_id)                    NOT NULL,
    name     VARCHAR(255)                                        NOT NULL,
    status   VARCHAR(255)                                        NOT NULL,
    created  TIMESTAMP WITHOUT TIME ZONE                         NOT NULL,
    updated  TIMESTAMP WITHOUT TIME ZONE                         NOT NULL,
    deleted  BOOLEAN DEFAULT FALSE
);