CREATE TABLE author
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    created     TIMESTAMP WITHOUT TIME ZONE,
    updated     TIMESTAMP WITHOUT TIME ZONE,
    deleted     BOOLEAN      NOT NULL,
    first_name  VARCHAR(255) NOT NULL,
    second_name VARCHAR(255) NOT NULL,
    patronymic  VARCHAR(255),
    email       VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE article_authors
(
    article_id BIGINT NOT NULL REFERENCES offer_article (id) ON DELETE CASCADE,
    author_id  BIGINT NOT NULL REFERENCES author (id) ON DELETE CASCADE,
    CONSTRAINT pk_article_authors PRIMARY KEY (article_id, author_id)
);