CREATE TABLE offer_article_answer
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    created                TIMESTAMP WITHOUT TIME ZONE,
    updated                TIMESTAMP WITHOUT TIME ZONE,
    deleted                BOOLEAN NOT NULL DEFAULT FALSE,
    version_id             BIGINT NOT NULL REFERENCES offer_article_version (id),
    documents_archive_uuid UUID REFERENCES file_metadata (uuid),
    comment                TEXT,
    is_draft               BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE article
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    created          TIMESTAMP WITHOUT TIME ZONE,
    updated          TIMESTAMP WITHOUT TIME ZONE,
    deleted          BOOLEAN NOT NULL DEFAULT FALSE,
    offer_article_id BIGINT NOT NULL REFERENCES offer_article (id),
    status           VARCHAR(255),
    comment          TEXT
);