---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jsms_db
    username: postgres
    password: postgres
  mail:
    username: username
    password: password
minio:
  url: http://localhost:9000
  username: minio
  password: minio_pass
#jwt:
#  secret:
#    access:
#    refresh: